### ISSUE TITLE
Stuck typing/error on note

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#148]
0|PROD-Swe | [15:52:48][ERROR][Dispatch:note]: DiscordAPIError: Invalid Form Body
0|PROD-Swe | content: Must be 2000 or fewer in length.
0|PROD-Swe |     at item.request.gen.end (/opt/skynet/Discord/sweeper-prod/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
0|PROD-Swe |     at then (/opt/skynet/Discord/sweeper-prod/node_modules/snekfetch/src/index.js:215:21)
0|PROD-Swe |     at <anonymous>
0|PROD-Swe |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
0|PROD-Swe | [15:53:13][LOG][CMD Warn]: Warned user: 'Light#0145' in '/r/DestinyTheGame'
0|PROD-Swe | [15:53:27][ERROR][Dispatch:note]: TypeError: Cannot read property 'id' of null
0|PROD-Swe |     at Note.<anonymous> (/opt/skynet/Discord/sweeper-prod/commands/modtools/Note.js:176:53)
0|PROD-Swe |     at Generator.next (<anonymous>)
0|PROD-Swe |     at fulfilled (/opt/skynet/Discord/sweeper-prod/commands/modtools/Note.js:4:58)
0|PROD-Swe |     at <anonymous>
0|PROD-Swe |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)

---

Snow was trying to add a note and did `.note UserID note text` and the bot ignored it. Possible error with missing the 1st argument (add/delete/etc).

**Comment by D0cR3d** [comment]
Issue caused a rename of the role it was looking for in the Note command. After changing role name back to normal, issue resolved. Also removed hard-coded role names as well.
